---
title: "R Notebook"
output: html_notebook
---

######################## The U.S. Energy Renaissance  ##################

```{r}
library(reshape2)
library(ggplot2)
library(dplyr)
library(shiny)
library(leaflet)
library(shinydashboard)
library(Quandl)
Quandl.api_key(api_key = "8u9meDr5sQxGim8ATVt6")
```


#### US IMPORTS OF NATURAL GAS ####

```{r - IMPORTS }
#Titles of columns and Quandl API code tickers
symbols_ng = list('EIA/NG_N9100US2_A', 'EIA/NG_N9103US2_A', 'EIA/NG_N9102US2_A')
symbols_ng_titles = list('Date', 'Total_Imports', 'LNG_Imports', 'Pipeline_Imports')

#Generate DF from Quandl API pull
imports = Quandl(symbols_ng, 
  start_date='01-01-1990', 
  end_date='01-01-2020', 
  collapse='annual')

colnames(imports) = symbols_ng_titles
imports[,-1] = round(imports[,-1]/1000000, digits = 1)


#Time Series 
ggplot(data=imports, aes(x=Date)) + 
  geom_line(aes(y=Total_Imports, colour='Total Imports')) + 
  geom_line(aes(y=LNG_Imports, colour='LNG Imports')) + 
  geom_line(aes(y=Pipeline_Imports, colour='Pipeline Imports')) + 
  scale_colour_manual("", 
    values=c('Total Imports'='blue','LNG Imports'='black', 'Pipeline Imports'='red')) + 
  labs(title='U.S. Natural Gas Imports') + 
  ylab('Billion Cubic Feet')

```


########### EXPORTS ##########


```{r - EXPORTS}
symbols2_ng = list('EIA/NG_N9130US2_M', 'EIA/NG_N9133US2_M', 'EIA/NG_N9132US2_M',
                   'EIA/PET_MNGEXUS1_M', 'EIA/PET_MPREXUS2_M')
symbols2_ng_titles = list('Date', 'Total_Exports', 'LNG_Exports', 
                          'Pipeline_Exports', 'NGL_Exports')

exports = Quandl(symbols2_ng, 
  start_date='01-01-1990', 
  end_date='01-01-2020',
  collapse='monthly')
tail(exports,20)

colnames(exports) = symbols2_ng_titles
exports[,-1] = round(exports[,-1]/1000, digits = 1)

#Melt Dataframe by Variabe and Value
df = melt(data=ngexports, id.vars = 'Date')

#Time Series of exports by natural gas product
ggplot(data=df, aes(x=Date, y=value, colour=variable)) + 
  geom_line() + 
  labs(title='U.S. Natural Gas Exports') + 
  xlab(label='Billion Cubic Feet')

```


###### PRODUCTION ######

```{r - PRODUCTION}
symbols_ngprod = list('EIA/NG_N9070US2_A', 'EIA/NG_N9050US2_A', 'EIA/NG_N9060US2_A')
titles_ngprod = list('Date', 'Dry_Natural_Gas', 'Marketed_Natural_Gas', 'Natural_Gas_Plant_Liquids')

ng_prod = Quandl(symbols_ngprod, 
  start_date='01-01-1990', 
  end_date='01-01-2020', 
  collapse='annual')

colnames(ng_prod) = titles_ngprod
ng_prod[,-1] = round(ng_prod[,-1]/1000, digits=1)
ng_prod

melt_df = melt(data = ng_prod, id.vars = 'Date')
ggplot(data=melt_df, aes(x=Date, y=value)) + 
  geom_line() +  
  facet_wrap(~variable, scales='free_y', ncol=1) + 
  xlab(label='Date') + 
  ylab(label='Billion Cubic Feet') + 
  labs(title='U.S. Natural Gas Production') 

```



```{r - SUPPLY}
ngsupply = Quandl('EIA/INTL_3_6_USA_TCF_A', 
  start_date='01-01-1980', 
  end_date = '01-01-2020')


ngsupply = ngsupply %>% arrange(Date)
ngsupply[nrow(ngsupply) + 1, ] = list(intl_ng$Date[40], 580) #Manually update 2019 annual reserve value for U.S.
colnames(ngsupply) = c('Date', 'Proven_Reserves') #Rename columns
ngsupply

#Time Series of U.S. Proven Reserves
plot(x=ngsupply$Date, 
  y=ngsupply$Proven_Reserves, 
  type='line',
  col='blue', 
  main='U.S. Natural Gas Proven Reserves', 
  xlab = 'Date', 
  ylab = 'Trillion Cubic Feet',
  lwd = 3,
  frame.plot = T, 
  tck = 1)

```


######## International Natural Gas Reserves ######## 

```{r - PROVEN RESERVES BY COUNTRY}
symbols_ng_reserves = list('EIA/INTL_3_6_SAU_TCF_A', 'EIA/INTL_3_6_RUS_TCF_A', 'EIA/INTL_3_6_USA_TCF_A', 'EIA/INTL_3_6_NOR_TCF_A', 'EIA/INTL_3_6_AFRC_TCF_A', 'EIA/INTL_3_6_AUS_TCF_A','EIA/INTL_3_6_CHN_TCF_A', 'EIA/INTL_3_6_NGA_TCF_A', 'EIA/INTL_3_6_IRN_TCF_A','EIA/INTL_3_6_QAT_TCF_A', 'EIA/INTL_3_6_CAN_TCF_A', 'EIA/INTL_3_6_VEN_TCF_A')

intl_ng_tickers = list('Date', 'Saudi Arabia', 'Russia', 'US', 'Norway', 'Africa', 'Australia', 'China', 'Nigeria', 'Iran', 'Qatar', 'Canada', 'Venezuela')

#Generate DF from Quandl API pull
intl_ng = Quandl(symbols_ng_reserves,
  start_date='01-01-1980', 
  end_date='01-01-2020',
  collapse='annual')

#Change dataframe columns names
colnames(intl_ng) = intl_ng_tickers
intl_ng[40,4] = 580 #Manually update 2019 annual reserve value for U.S.
intl_ng

#Bar Chart of Countries w/Highest Reserves
a = sort(as.vector(intl_ng[nrow(intl_ng),-1]), decreasing = T)
barplot(as.numeric(a[,1:5]), 
  names.arg = colnames(a[1:5]), 
  main = 'International Natural Gas Reserves',
  ylab = 'Trillion Cubic Feet',
  ylim = c(0,2000), 
  width = 1,
  col = c('green', 'blue', 'black', 'red', 'yellow'))

```




